---
version: "3.8"

x-service: &service-common
  deploy:
    restart_policy:
      condition: on-failure
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=US/Pacific
    - UMASK_SET=022

services:
  sonarr:
    <<: *service-common
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./config/sonarr:/config
      - /mnt/brainslug/media:/media
    ports: [8989:8989]
    
  radarr:
    <<: *service-common
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ./config/radarr:/config
      - /mnt/brainslug/media:/media
    ports: [7878:7878]

  lidarr:
    <<: *service-common
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - ./config/lidarr:/config
      - /mnt/brainslug/media:/media
    ports: [8686:8686]

  sabnzbd:
    <<: *service-common
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    volumes:
      - ./config/sabnzbd:/config
      - /mnt/brainslug/media:/media
    ports: [8080:8080]
